stages:
    - deploy
 
deploy-master:
    stage: deploy
    script:
      - "ssh 46.101.159.24 -p 22 -l root 'cd ~/pbmail/ && git stash && git pull && pkill -9 php && composer install && sh ./start.sh'"
    only:
      - master
    except:
      - development
    retry: 1
    