stages:
    - deploy
    - test
 
deploy-master:
    stage: deploy
    script:
      - "ssh 46.101.159.24 -p 22 -l root 'cd ~/pbmail/ && git stash && git pull && pkill -9 php && composer install && sh ./start.sh'"
    only:
      - master
    except:
      - development
    retry: 1
    
test-development:
    stage: test
    script:
      - "ssh 167.172.155.151 -p 22 -l root 'cd ~/pbmail-server/ && git stash && git pull && pkill -9 php && composer install && sh ./start.sh'"
    only:
      - development
    except:
      - master
    retry: 1
    